### ISSUE TITLE
Reading from closed file handle causes a segfault

### ISSUE THREAD

**Issue by pt9999** [tttmmmyyyy/fixlang#47]
If you call `read_line()` after `close_file()`, it causes a segmentation fault.

日本語による説明:
`close_file()`でファイルハンドルを閉じたあとに`read_line()`を呼び出すとsegfaultするようです。
おそらくread時にファイルハンドルがnullかどうかのチェックが必要だと思います。

Sample code:
```
module Main;
main: IO ();
main = do {
    let fh = *open_file(Path::parse("/dev/null").as_some, "r");
    eval *close_file(fh).lift;
    let line = *read_line(fh);
    println(line).lift
}.try(eprintln);
```

**Comment by tttmmmyyyy** [comment]
ご報告ありがとうございました。ご指摘の通りの方法（nullチェック）で修正しようと思います。

なお、同じIOHandleを複数のスレッドで共有している場合、あるスレッドでnullチェックしてからfgetsするまでの間に、ほかのスレッドでfcloseが行われ、同様の問題が発生する可能性はあります。
ただし、そもそも、C言語標準関数の仕様として、同じFILE*を複数スレッドで共有し、同時に複数スレッドからfgetsやfcloseすることが未定義動作のように思えます（ただし、未だはっきりとしたエビデンスが得られていません）ので、マルチスレッドの状況下では、仮にこのIssueの現象を回避したとしても、未定義動作を避けることはできないと考えています。
そのため、今回の修正では、IOHandleを複数スレッドで共有しているケースについては考慮しないことにしました。

Rustのように「スレッド間で共有できない型」を定義できたほうが良いのかもしれません。（ただし、マルチスレッド非対応な型を共有しようとしていることをコンパイル時に検出するのはFixでは難しいので、可能だとしても実行時のチェックになります。）
